[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "automate"
version = "0.1.0"
description = "Toy calculator project for learning CI/CD"
authors = [{ name = "Muhammad Dawood" }]
